version: 2
services:
  backend:
    source: .
    build:
      commands:
        - go build -o main cmd/api/main.go
    start: ./main
    environment:
      PORT: 8080
      DATABASE_URL: ${{Postgres.DATABASE_URL}}
  
  frontend:
    source: .
    build:
      commands:
        - npm install
        - npm run build
    start: npx serve -s dist -p $PORT
    environment:
      VITE_API_BASE_URL: https://${{backend.RAILWAY_PUBLIC_DOMAIN}}
      
plugins:
  - type: postgresql